version: '3.7'

services:
  e-commerce:
    container_name: e-commerce
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
