export const GET_SHOPPING_CART_CONTENT = "GET_SHOPPING_CART_CONTENT";
export const CREATE_ITEM_SHOPPING_CART = "CREATE_ITEM_SHOPPING_CART";
export const REMOVE_ITEM_SHOPPING_CART = "REMOVE_ITEM_SHOPPING_CART";
export const INCREMENT_QUANTITY_SHOPPING_CART =
  "INCREMENT_QUANTITY_SHOPPING_CART";
